import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const ibmPlexSans = IBM_Plex_Sans({
   variable: "--font-ibm-plex",
   subsets: ["latin"],
   weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en" suppressHydrationWarning className={`${ibmPlexSans.variable} h-full antialiased`}>
         <body className={`${ibmPlexSans.className} h-full bg-slate-950 text-slate-100 dark`}>{children}</body>
      </html>
   );
}
