import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider"; // sesuaikan path file kamu

const ibmPlexSans = IBM_Plex_Sans({
   variable: "--font-ibm-plex",
   subsets: ["latin"],
   weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      
      <html lang="en" suppressHydrationWarning className={`${ibmPlexSans.variable} h-full antialiased`}>
         <body className={`${ibmPlexSans.className} h-full bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 transition-colors duration-300`}>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}